### ISSUE TITLE
Are the evaluation results from `MGSM` or `MGSM8KInstruct`?

### ISSUE THREAD

**Issue by zhimin-z** [microsoft/MathOctopus#7]
Check https://mathoctopus.github.io/ but found:
<img width="804" alt="1710723616790" src="https://github.com/microsoft/MathOctopus/assets/8592144/b528e85b-2632-43bb-8660-bb7943979b78">
Are these evaluation results from `MGSM` or `MGSM8KInstruct`?

**Comment by jerrynchen** [comment]
Thanks for your question! MGSM8KInstruct is the training dataset while MGSM is the test dataset
